const C=SITE_CONTENT; const $=id=>document.getElementById(id);
function txt(id,v){if($(id))$(id).textContent=v||""}function paras(id,a){$(id).innerHTML=(a||[]).map(x=>`<p>${x}</p>`).join("")}
function links(id,a){$(id).innerHTML=(a||[]).map(x=>`<a href="${x.url}" ${x.url.startsWith('http')?'target="_blank" rel="noopener"':''}>${x.text}</a>`).join("")}
txt('navName',C.profile.nameCn);txt('navNameEn',C.profile.nameEn);txt('nameCn',C.profile.nameCn);txt('nameEn',C.profile.nameEn);txt('position',C.profile.position);txt('affiliation',C.profile.affiliation);txt('affiliation2',C.profile.affiliation2);txt('headline',C.profile.headline);$('portrait').src=C.profile.portrait;paras('bio',C.profile.bio);links('profileLinks',C.profile.links);
$('highlights').innerHTML=C.profile.highlights.map(x=>`<div class="highlight"><b>${x.value}</b><span>${x.label}</span></div>`).join('');
$('researchCards').innerHTML=C.research.map((x,i)=>`<article class="card"><span class="num">${String(i+1).padStart(2,'0')}</span><h3>${x.title}</h3><p>${x.description}</p></article>`).join('');txt('methods',C.methods);
$('education').innerHTML=C.education.map(x=>`<div class="row"><div class="time">${x.time}</div><div><b>${x.place}</b><small>${x.detail}</small></div></div>`).join('');
function isZh(p){return p.language==='中文'||/[\u4e00-\u9fff]/.test(p.title)}function renderPubs(filter='all'){$('publicationList').innerHTML=PUBLICATIONS.filter(p=>filter==='all'||(filter==='zh'&&isZh(p))||(filter==='en'&&!isZh(p))).map(p=>`<article class="pub"><div class="pubyear">${p.year}</div><div><div class="pubtitle">${p.title}${p.url?` <a class="doi" href="${p.url}" target="_blank">DOI ↗</a>`:''}</div><div class="pubmeta">${p.authors} · ${p.journal}</div></div><div class="tag">${p.tag||''}</div></article>`).join('')};renderPubs();document.querySelectorAll('.filterbar button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filterbar button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderPubs(b.dataset.filter)});
$('projectList').innerHTML=C.projects.map(p=>`<article class="project"><div class="role">${p.role}</div><div><h3>${p.title}</h3><p>${p.description}</p></div></article>`).join('');
txt('teamIntro',C.team.intro);$('teamCategories').innerHTML=C.team.categories.map(x=>`<div class="teambox"><h3>${x.title}</h3><p>${x.text}</p></div>`).join('');if(C.team.members&&C.team.members.length){$('teamMembers').className='members';$('teamMembers').innerHTML='<h3>团队成员</h3>'+C.team.members.map(m=>`<div class="member"><b>${m.name}</b> · ${m.degree}<br><small>${m.interest}</small></div>`).join('')}txt('teamNote',C.team.note);
$('courses').innerHTML=C.teaching.courses.map(x=>`<span>${x}</span>`).join('');$('awards').innerHTML=C.teaching.awards.map(x=>`<li>${x}</li>`).join('');$('service').innerHTML=C.service.map(x=>`<li>${x}</li>`).join('');
txt('contactAddress',C.contact.address);$('contactEmail').href='mailto:'+C.contact.email;$('contactEmail').textContent=C.contact.email;txt('year',new Date().getFullYear());
const mb=document.querySelector('.menubtn'),nav=$('nav');mb.onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));
